/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_units_geometry_Geometry */

#ifndef _Included_com_units_geometry_Geometry
#define _Included_com_units_geometry_Geometry
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_units_geometry_Geometry
 * Method:    getRectangleArea
 * Signature: (Lcom/units/geometry/Rectangle;)I
 */
JNIEXPORT jint JNICALL Java_com_units_geometry_Geometry_getRectangleArea
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
